### ISSUE TITLE
Time dialog: how to set am / pm in graphical mode

### ISSUE THREAD

**Issue by hitzg** [BlueM/Pashua#7] opened 2018-04-23 15:27 UTC
When launching this configuration: 
```
d.type = date
d.label = Example date
d.default = 2007-05-30 17:00
d.time = 1
```
I get this dialog (which looks slightly different than the one in the [docs](https://www.bluem.net/pashua-docs-latest.html#element.date)):
![screen shot 2018-04-23 at 17 18 26](https://user-images.githubusercontent.com/688395/39136450-92524250-471b-11e8-961f-34a4e05b7518.png)

How can the user see wether the time is AM or PM?

PS: I'm on OS X 10.11.6, Pashua v 0.10.3

**Comment by BlueM** [comment] 2018-04-23 17:41
To be honest: I don’t know. The screenshot from the docs, which you mention, shows a dimmed “nachm.” text – which is an abbreviation of the German “nachmittags” (obviously I took the screenshot from my normal account, which has German as language), which approximately means “PM”. But: this screenshot is pretty dated, and it seems – I hadn’t noticed that until your issue – that Apple, in their usual infinite wisdom, have decided that this information is superfluous and dropped it. (On 10.12, I don’t have this, too.)

So I’d say the answer is: if you need the time, too, the graphical mode is pretty useless, so you switch it to textual mode using `d.textual = 1`.

**Comment by hitzg** [comment] 2018-04-24 09:46
I speak German as well, and thus assumed that there might be a (hidden) flag somewhere to turn it on. But since this one is on Apple, there's probably nothing we can do about it ;-)
I already suspected that I'll have to use the textual mode.

**Comment by BlueM** [comment] 2018-04-24 10:07
I have no idea when this was dropped. (And, BTW, sitting in front of a 10.13 Mac yesterday, I verified that it hasn’t returned in 10.13.) One more – albeit tiny – thing Apple managed to fuck up in OS X / macOS.

**Comment by hitzg** [comment] 2018-04-24 12:18
Sorry for dwelling on this, but weirdly in the system preferences the am/pm label is still there!

![image](https://user-images.githubusercontent.com/688395/39186307-55e2783a-47ca-11e8-81cc-9d6f0012588a.png)

**Comment by BlueM** [comment] 2018-04-24 20:16
Just checked with Xcode’s visual GUI builder: even in that case, I don’t get “AM”/“PM” – and I see nothing which lets me change this (like I didn’t find anything in the docs to change this via code). So it looks like the problem is not how Pashua programmatically sets up the control, but rather lies in Cocoa itself.

I’ll leave this issue open, in case someone else has an idea how the graphical timepicker can be modified to be usable. (Thanks again, Apple.)

**Comment by jorisroling** [comment] 2018-10-24 11:57
I'm on Mojave, but I do see it (OS region = Netherlands).
![screenshot 2018-10-24 at 13 55 45](https://user-images.githubusercontent.com/635729/47428807-a9480080-d794-11e8-9491-5acccf54785e.png)

**Comment by BlueM** [comment] 2018-10-25 20:21
Thanks for verifying this. I just verified it on a German Mojave, and it works indeed – with the last official version and, of course, no code changes. Which, IMHO, leaves no doubt that this is/was a Cocoa bug that has been fixed in Mojave.

So, to conclude, the problem is related to the OS X / macOS version and cannot be fixed by Pashua.

**Closed by BlueM** 2018-10-25 20:21 UTC
Labels: help wanted, question
